version: "3.3"

services:
  bookstore_users_api:
    build: bookstore_users-api
    restart: always
    ports:
      - "${BOOKSTORE_PORT}:${BOOKSTORE_PORT}"
    volumes:
      - bookstore_users-api:/app
    depends_on:
      - bookstore_users_api_mysql_db

  bookstore_users_api_mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${BOOKSTORE_USERS_API_MYSQL_DATABASE}
      MYSQL_USER: ${BOOKSTORE_USERS_API_MYSQL_USER}
      MYSQL_PASSWORD: ${BOOKSTORE_USERS_API_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${BOOKSTORE_USERS_API_MYSQL_ROOT_DATABASE}

    ports:
      - "${BOOKSTORE_USERS_API_PORT}:3306"
    expose:
      - "${BOOKSTORE_USERS_API_PORT}"
    volumes:
      - bookstore_users_api_db:/var/lib/mysql

volumes:
  bookstore_users_api_db:
  bookstore_users-api: